### ISSUE TITLE
setup.py issue in Windows 10

### ISSUE THREAD

**Issue by aiolosyuan** [abhishek-vinjamoori/SubtitleExtractor#19]
========================== RESTART: C:\se\setup.py ==========================

Warning (from warnings module):
  File "C:\Python36\lib\site-packages\bs4\__init__.py", line 146
    warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
Traceback (most recent call last):
  File "C:\se\setup.py", line 115, in <module>
    main()
  File "C:\se\setup.py", line 106, in main
    updateServices[services]()
  File "C:\se\setup.py", line 70, in amazonUpdate
    pageSource = BeautifulSoup(pageSource, "lxml", from_encoding="utf8").pre.text
  File "C:\Python36\lib\site-packages\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by lindseywilliams90** [comment]
You need to install lxml and requests but yea, I have problem with encoding too.
